from enum import Enum

class Tagset ( Enum ):
    NN = 'Noun'
    CND = 'Conditional'
    CNJ = 'Conjunction'
    POP = 'Postposition'
    DIS = 'Disjunction'
    NEG = 'Negative particle'
    ING = 'Interrogative particle'
    INT = 'Interjection'
    VF = 'Finite verb'
    QFNUM = 'Quantifier number'
    NV = 'Verbal Noun'
    AV = 'Verbal Adjective'
    AD = 'Adjective'
    ADA = 'Adjective of adjective'
    PP = 'Pronoun'
    PPP = 'Possesive Pronoun'
    SYM = 'Symbol'
    VNF = 'Nonfinite verb'
